name: "keypoints-infer"
platform: "tensorrt_plan"
max_batch_size: 8
input: [
    {
        name: "images",
        data_type: TYPE_FP32,
        dims: [
            3,
            960,
            960
        ]
    }
]
output: [
    {
        name: "output",
        data_type: TYPE_FP32,
        dims: [
            -1,
            -1
        ]
    }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
dynamic_batching { }
version_policy: { all { }}
model_warmup [{
    name : "keypoints-infer"
    batch_size: 8
    inputs {
        key: "images"
        value: {
            data_type: TYPE_FP32
            dims: [ 3, 960, 960 ]
            random_data : True
        }
    }
}]